AllCops:
  Include:
    - Rakefile
    - config.ru
    - app/views/**/*.rabl
  Exclude:
    - db/**/*
    - doc/**
    - config/**/*
    - script/**
    - bin/*
    - Rakefile
    - config.ru
    - vendor/*
    - sh/*
    - gems/**
    - gems/*/vendor/**

AccessorMethodName:
  Enabled: false

Alias:
  Enabled: false

Blocks:
  Enabled: false

ClassLength:
  Max: 120

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Documentation:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Max: 30

HasAndBelongsToMany:
  Enabled: false

TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
